fig=figure('Units','inches',...
'Position',[5 5 5 3],...
'PaperPositionMode','auto');

scatter(scatterx,scattery,scatterr2,scatterc, 'filled', 'MarkerEdgeColor', 'k')
colormap(winter)
%clear xlabel

axis([0 8 0 1.1])

set(gca,...
'XTick',1:6, 'XTickLabel',1:6,...
...%'YTick',1:16, 'YTickLabel',11:26,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',10,...
'FontName','Helvetica')

ylabel({'Packet Success'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',10,...
'FontName','Helvetica')

xlabel('Measurement No',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',10,...
'FontName','Helvetica')

%view([270 90])
c=colorbar('east');
ax = gca;
axpos = ax.Position;
cpos = c.Position;

cpos(3) = 0.5*cpos(3);
c.Position = cpos;
ax.Position = axpos;



print(fig,'scatterreliability','-dpdf','-r0')